import os
import yasha.scons

env = Environment(
    ENV = os.environ,
    BUILDERS = {"Yasha": yasha.scons.CBuilder()}
)

duplicate = 0 # See how the duplication affects to the file paths
env.VariantDir("build", "src", duplicate=duplicate)

sources = ["build/main.c"]

if duplicate:
    templates = ["build/foo.c.jinja", "build/foo.h.jinja"]
    generated = env.Yasha(templates)
    env.Depends(generated, "build/foo.toml")

else:
    templates = ["src/foo.c.jinja", "src/foo.h.jinja"]
    generated = env.Yasha(templates)
    env.Depends(generated, "src/foo.toml")

sources += generated
env.Program("build/a.out", sources)
env.Decider("timestamp-newer") # Added due to unit testing
