# With variant dir

import os
import yasha.scons

env = Environment(
    ENV = os.environ,
    BUILDERS = {
        "Yasha": yasha.scons.CBuilder()
    }
)

env.VariantDir("build", "src", duplicate=0) # duplicate=1 doesn't work

sources = ["build/main.c"]
sources += env.Yasha(["src/foo.c.jinja", "src/foo.h.jinja"])

prog = env.Program("build/a.out", sources)
env.Decider("timestamp-newer") # Added due to unit testing
