# Without variant dir

import os
import yasha.scons

env = Environment(
    ENV = os.environ,
    BUILDERS = {"Yasha": yasha.scons.CBuilder()}
)

sources = ["main.c"]
templates = ["foo.c.jinja", "foo.h.jinja"]

generated = env.Yasha(templates)
env.Depends(generated, "foo.toml")

sources += generated
env.Program("a.out", sources)
env.Decider("timestamp-newer") # Added due to unit testing
