# Without variant dir

import os
import yasha.scons

env = Environment(
    ENV = os.environ,
    BUILDERS = {'Yasha': yasha.scons.CBuilder()}
)

templates = Glob('*.jinja')
sources = ['main.c'] + env.Yasha(templates)

env.Program('a.out', sources)
env.Decider('make') # Added due to unit testing
